SmartParkInnovate/Controllers/ParkingController.cs
using Microsoft.AspNetCore.Mvc;
using SmartParkInnovate.Core.Contracts;
using SmartParkInnovate.Core.Models.ParkingSpot;
using SmartParkInnovate.Core.Models.ParkingSpotModel;
using SmartParkInnovate.Core.Models.VehicleModel;
using System.Security.Claims;

namespace SmartParkInnovate.Controllers
{
    public class ParkingController : BaseController
    {
        private readonly IParkingService parkingService;

        public ParkingController(IParkingService parkingService)
        {
            this.parkingService = parkingService;
        }

        [HttpGet]
        public async Task<IActionResult> ParkingSpots()
        {
            IEnumerable<ParkingSpotViewModel> parkingSpots = await this.parkingService.ParkingSpots();
            return View(parkingSpots);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                string userId = User.Id();
                ParkingSpotDetailsModel parkingSpot = await this.parkingService.Details(id, userId);

                return View(parkingSpot);
            }
            catch (ArgumentException argException)
            {
                return this.HandleErrorMessage(argException.Message);
            }
            catch(InvalidOperationException ioe)
            {
                return this.HandleErrorMessage(ioe.Message);
            }
        }

        [HttpGet]
        public IActionResult UseSpot(int id)
        {
            UseSpotVehicleFormModel model = new UseSpotVehicleFormModel();

            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> UseSpot(int id, UseSpotVehicleFormModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            try
            {
                string userId = User.Id();
                await this.parkingService.Use(id, userId, model);

                return RedirectToAction(nameof(ParkingSpots));
            }
            catch (ArgumentException argException)
            {
                return this.HandleErrorMessage(argException.Message);
            }
            catch (InvalidOperationException ioe)
            {
                return this.HandleErrorMessage(ioe.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> ExitSpot(int id)
        {
            try
            {
                string userId = User.Id();
                await this.parkingService.Exit(id, userId);

                return RedirectToAction(nameof(ParkingSpots));
            }
            catch (ArgumentException argException) 
            {
                return this.HandleErrorMessage(argException.Message);
            }
            catch (InvalidOperationException ioe)
            {
                return this.HandleErrorMessage(ioe.Message);

            }
        }
    }
}

SmartParkInnovate/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using SmartParkInnovate.Core.Contracts;
using SmartParkInnovate.Core.Models.CommentModel;
using SmartParkInnovate.Core.Models.PostModel;
using System.Security.Claims;

namespace SmartParkInnovate.Controllers
{
    public class PostController : BaseController
    {
        private readonly IPostService postService;

        public PostController(IPostService postService)
        {
            this.postService = postService;
        }

        [HttpGet]
        public async Task<IActionResult> Posts()
        {
            IEnumerable<PostViewModel> posts = await this.postService.All();

            return View(posts);
        }

        [HttpGet]
        public IActionResult PublishPost()
        {
            PostFormModel model = new PostFormModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> PublishPost(PostFormModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            try
            {
                string userId = User.Id();
                await this.postService.Add(userId, model);

                return RedirectToAction(nameof(Posts));
            }
            catch (ArgumentException argException)
            {
                return this.HandleErrorMessage(argException.Message);
            }
            catch (InvalidOperationException ioe)
            {
                return this.HandleErrorMessage(ioe.Message);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            string userId = User.Id();
            PostDetailModel model = await this.postService.Details(userId, id);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> LikePost(int id)
        {
            try
            {
                string userId = User.Id();
                await this.postService.LikePost(id, userId);

                return RedirectToAction(nameof(Details), new { id });
            }
            catch (ArgumentException argException)
            {
                return this.HandleErrorMessage(argException.Message);
            }
            catch (InvalidOperationException ioe)
            {
                return this.HandleErrorMessage(ioe.Message);
            }
        }

        [HttpGet]
        public IActionResult CommentPost(int id)
        {
            CommentFormModel model = new CommentFormModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CommentPost(int id, CommentFormModel comment)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            try
            {
                string userId = User.Id();
                await this.postService.Comment(id, userId, comment);

                return RedirectToAction(nameof(Details), new { id });
            }
            catch (ArgumentException argException)
            {
                return this.HandleErrorMessage(argException.Message);
            }
            catch (InvalidOperationException ioe)
            {
                return this.HandleErrorMessage(ioe.Message);
            }
        }

        [HttpGet]
        public async Task<IActionResult> EditPost(int id)
        {
            PostFormModel model = await this.postService.GetPostById(id);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditPost(int id, PostFormModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            try
            {
                string currentUser = User.Id();
                await this.postService.Edit(id, currentUser, model);

                return RedirectToAction(nameof(Details), new { id });
            }
            catch (ArgumentException argException)
            {
                return this.HandleErrorMessage(argException.Message);
            }
            catch (InvalidOperationException ioe)
            {
                return this.HandleErrorMessage(ioe.Message);
            }
        }

    }
}

SmartParkInnovate/Controllers/VehicleController.cs
using Microsoft.AspNetCore.Mvc;
using SmartParkInnovate.Core.Contracts;
using SmartParkInnovate.Core.Models.VehicleModel;
using System.Security.Claims;

namespace SmartParkInnovate.Controllers
{
    public class VehicleController : BaseController
    {
        private readonly IVehicleService vehicleService;

        public VehicleController(IVehicleService vehicleService)
        {
            this.vehicleService = vehicleService;
        }

        [HttpGet]
        public IActionResult AddVehicle()
        {
            VehicleFormModel formModel = new VehicleFormModel();

            return View(formModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddVehicle(VehicleFormModel formModel)
        {
            string userId = User.Id();

            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            try
            {
                await this.vehicleService.Add(userId, formModel);
                return RedirectToAction(nameof(Vehicles));
            }
            catch (ArgumentException argException)
            {
                return this.HandleErrorMessage(argException.Message);
            }
            catch (InvalidOperationException ioe)
            {
                return this.HandleErrorMessage(ioe.Message);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Vehicles()
        {
            string userId = User.Id();

            IEnumerable<VehicleViewModel> vehicles = await this.vehicleService.MyVehicles(userId);

            return View(vehicles);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            string userId = User.Id();

            try
            {
                VehicleDetailsViewModel model = await this.vehicleService.Details(id, userId);
                return View(model);
            }
            catch (ArgumentException argException)
            {
                return this.HandleErrorMessage(argException.Message);
            }
        }
    }
}

SmartParkInnovate/Areas/Admin/Views/Shared/AdminCustomError.cshtml
@model string

<body style="background-color: #4C98CF;">
    <h3 style="color: #FF667E">@Model</h3>
</body>

SmartParkInnovate/Areas/Admin/Views/Shared/_AdminPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Security.Claims;

@inject SignInManager<Worker> SignInManager
@inject UserManager<Worker> UserManager

@{
    string userName = string.Empty;

    if (SignInManager.IsSignedIn(User))
    {
        Worker user = await UserManager.FindByIdAsync(User.Id());
        userName = User.FindFirstValue(SmartParkInnovate.Infrastructure.Extensions.CustomClaims.UserFirstNameClaim) ?? string.Empty;
    }
}


<ul class="navbar-nav">
    @if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <p class="nav-link text-light" style="color: #CCE5EA">Hello, @userName</p>
        </li>
        <li class="nav-item">
            <a class="nav-link text-light" style="color:#CCE5EA" asp-area="" asp-controller="Home" asp-action="Index">Back To System</a>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link text-light" style="color:#CCE5EA" asp-area="Identity" asp-page="/Account/Register">Register</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-light" style="color:#CCE5EA" asp-area="Identity" asp-page="/Account/Login">Login</a>
        </li>
    }
</ul>

SmartParkInnovate/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SmartParkInnovate</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SmartParkInnovate.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="outset navbar navbar-expand-sm navbar-toggleable-sm navbar-light" style="background-color: #4C99CF">
            <div class="container-fluid">
                <a class="navbar-brand" style="color:#CCE5EA" asp-area="" asp-controller="Home" asp-action="Index">SmartParkInnovate</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" style="color:#CCE5EA" asp-area="Admin" asp-controller="Home" asp-action="Dashboard">Dashboard</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" style="color:#CCE5EA" asp-area="Admin" asp-controller="Parking" asp-action="ParkingSpots">Manage Parking Spots</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" style="color:#CCE5EA" asp-area="Admin" asp-controller="Parking" asp-action="ParkingOccupations">View Occupations History</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" style="color:#CCE5EA" asp-area="Admin" asp-controller="Vehicle" asp-action="Vehicles">Manage Vehicles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" style="color:#CCE5EA" asp-area="Admin" asp-controller="Post" asp-action="Posts">Manage Posts</a>
                            </li>
                        }
                    </ul>
                    <partial name="_AdminPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="footer text-muted" style="background-color: #4C98CF">
        <div class="container" style="color: #CCE5EA">
            &copy; @DateTime.Today.Year - <span class="text-danger">Admin Only Area</span>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>